FROM alpine:3.9
RUN apk --update add ca-certificates

FROM golang:1.12
WORKDIR /app
COPY ./ ./
RUN GOOS=linux CGO_ENABLED=0 go build -o ./controller ./cmd/controller

FROM scratch
COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=1 /app/controller /bin/controller
ENTRYPOINT ["/bin/controller"]
