#!/bin/bash
set -e

OS_PLATFORM_ARG=(linux windows darwin)

declare -A OS_ARCH_ARG
OS_ARCH_ARG[linux]="amd64 arm arm64"
OS_ARCH_ARG[windows]="386 amd64"
OS_ARCH_ARG[darwin]="amd64"

for OS in ${OS_PLATFORM_ARG[@]}; do
    for ARCH in ${OS_ARCH_ARG[${OS}]}; do
        SOURCE="s3://downloads.deviceplane.com/cli/latest/${OS}/${ARCH}/deviceplane"
        REDIRECT="/${CLI_VERSION}/${OS}/${ARCH}/deviceplane"
        if test "$OS" = "windows"; then
            SOURCE="${SOURCE}.exe"
            REDIRECT="${REDIRECT}.exe"
        fi
        aws s3 cp empty ${SOURCE} --website-redirect ${REDIRECT}
    done
done
