#!/bin/bash
set -ex

mkdir -p ./dist/cli

if ! git log -1 | grep -q "Release CLI"; then
  exit 0
fi

sudo pip install awscli
CLI_VERSION=$(git log -1 --pretty=%B | grep "Release CLI" | cut -d ' ' -f3) upload-cli-binary-redirects
