/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker';
// tslint:disable:object-literal-key-quotes

export const Props = t.iface([], {
  query: 'Query',
  canRemoveFilter: 'boolean',
  removeFilter: t.opt(t.func('void', t.param('index', 'number'))),
});

export const State = t.iface([], {});

const exportedTypeSuite: t.ITypeSuite = {
  Props,
  State,
};
export default exportedTypeSuite;
