/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker';
// tslint:disable:object-literal-key-quotes

export const Query = t.array('Filter');

export const Filter = t.array('Condition');

export const Condition = t.iface([], {
  type: 'ConditionType',
  params: 'ConditionParams',
  options: t.iface([], {}),
});

export const ConditionType = t.name('string');

export const ConditionParams = t.union(
  'DevicePropertyConditionParams',
  'LabelValueConditionParams',
  'LabelExistenceConditionParams'
);

export const DevicePropertyConditionParams = t.iface([], {
  property: 'string',
  operator: 'Operator',
  value: 'string',
});

export const LabelValueConditionParams = t.iface([], {
  key: 'string',
  operator: 'Operator',
  value: 'string',
});

export const LabelExistenceConditionParams = t.iface([], {
  key: 'string',
  operator: 'Operator',
});

export const Operator = t.name('string');

const exportedTypeSuite: t.ITypeSuite = {
  Query,
  Filter,
  Condition,
  ConditionType,
  ConditionParams,
  DevicePropertyConditionParams,
  LabelValueConditionParams,
  LabelExistenceConditionParams,
  Operator,
};
export default exportedTypeSuite;
