/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker';
// tslint:disable:object-literal-key-quotes

export const Props = t.iface([], {
  setterEndpoint: 'string',
  configs: t.array('realConfig'),
});

export const State = t.iface([], {
  configs: t.array('editableConfig'),
});

export const realConfig = t.iface([], {
  metric: 'string',
  labels: t.array('string'),
  tags: t.array('string'),
});

export const editableConfig = t.iface([], {
  values: 'configStringValues',
  editedValues: t.opt('configStringValues'),
  mode: 'string',
});

export const configStringValues = t.iface([], {
  metricStr: 'string',
  labelsStr: 'string',
  tagsStr: 'string',
});

const exportedTypeSuite: t.ITypeSuite = {
  Props,
  State,
  realConfig,
  editableConfig,
  configStringValues,
};
export default exportedTypeSuite;
