#!/bin/bash
set -e

if [ -z "$CLI_VERSION" ]; then
    echo "CLI_VERSION not set"
    exit 1
fi

docker build -t deviceplane/cli:${CLI_VERSION} -f dockerfiles/cli/Dockerfile --build-arg version=${CLI_VERSION} .
