#!/bin/bash
set -e

if [ -z "$CONTROLLER_VERSION" ]; then
    echo "CONTROLLER_VERSION not set"
    exit 1
fi

docker build -t deviceplane/controller:${CONTROLLER_VERSION} -f dockerfiles/controller/Dockerfile --build-arg version=${CONTROLLER_VERSION} .
