#!/bin/bash
set -e

docker build -t deviceplane/agent:amd64-${VERSION} -f dockerfiles/agent/amd64/Dockerfile --build-arg version=${VERSION} .
docker build -t deviceplane/agent:arm32v6-${VERSION} -f dockerfiles/agent/arm32v6/Dockerfile --build-arg version=${VERSION} .
docker build -t deviceplane/agent:arm64v8-${VERSION} -f dockerfiles/agent/arm64v8/Dockerfile --build-arg version=${VERSION} .

docker push deviceplane/agent:amd64-${VERSION}
docker push deviceplane/agent:arm32v6-${VERSION}
docker push deviceplane/agent:arm64v8-${VERSION}

docker manifest create deviceplane/agent:${VERSION} deviceplane/agent:amd64-${VERSION} deviceplane/agent:arm32v6-${VERSION} deviceplane/agent:arm64v8-${VERSION}
docker manifest annotate deviceplane/agent:${VERSION} deviceplane/agent:arm32v6-${VERSION} --os linux --arch arm
docker manifest annotate deviceplane/agent:${VERSION} deviceplane/agent:arm64v8-${VERSION} --os linux --arch arm64 --variant armv8
