#!/bin/bash
set -e

docker build -t deviceplane/agent:amd64-${VERSION} -f dockerfiles/agent/Dockerfile.amd64 --build-arg version=${VERSION} .
docker build -t deviceplane/agent:arm32v6-${VERSION} -f dockerfiles/agent/Dockerfile.arm32v6 --build-arg version=${VERSION} .
docker build -t deviceplane/agent:arm64v8-${VERSION} -f dockerfiles/agent/Dockerfile.arm64v8 --build-arg version=${VERSION} .

docker push deviceplane/agent:amd64-${VERSION}
docker push deviceplane/agent:arm32v6-${VERSION}
docker push deviceplane/agent:arm64v8-${VERSION}

docker manifest create deviceplane/agent:${VERSION} deviceplane/agent:amd64-${VERSION} deviceplane/agent:arm32v6-${VERSION} deviceplane/agent:arm64v8-${VERSION}
docker manifest annotate deviceplane/agent:${VERSION} deviceplane/agent:arm32v6-${VERSION} --os linux --arch arm
docker manifest annotate deviceplane/agent:${VERSION} deviceplane/agent:arm64v8-${VERSION} --os linux --arch arm64 --variant armv8
