#!/bin/bash
set -e

if [ -z "$AGENT_VERSION" ]; then
    echo "AGENT_VERSION not set"
    exit 1
fi

docker build -t deviceplane/agent:amd64-${AGENT_VERSION} -f dockerfiles/agent/amd64/Dockerfile --build-arg version=${AGENT_VERSION} .
docker build -t deviceplane/agent:arm32v6-${AGENT_VERSION} -f dockerfiles/agent/arm32v6/Dockerfile --build-arg version=${AGENT_VERSION} .
docker build -t deviceplane/agent:arm64v8-${AGENT_VERSION} -f dockerfiles/agent/arm64v8/Dockerfile --build-arg version=${AGENT_VERSION} .

docker push deviceplane/agent:amd64-${AGENT_VERSION}
docker push deviceplane/agent:arm32v6-${AGENT_VERSION}
docker push deviceplane/agent:arm64v8-${AGENT_VERSION}

docker manifest create deviceplane/agent:${AGENT_VERSION} deviceplane/agent:amd64-${AGENT_VERSION} deviceplane/agent:arm32v6-${AGENT_VERSION} deviceplane/agent:arm64v8-${AGENT_VERSION}
docker manifest annotate deviceplane/agent:${AGENT_VERSION} deviceplane/agent:arm32v6-${AGENT_VERSION} --os linux --arch arm
docker manifest annotate deviceplane/agent:${AGENT_VERSION} deviceplane/agent:arm64v8-${AGENT_VERSION} --os linux --arch arm64
