#!/bin/bash
set -e

if [ -z "$CONTROLLER_VERSION" ]; then
    echo "CONTROLLER_VERSION not set"
    exit 1
fi

docker build -t gcr.io/focal-freedom-236620/deviceplane-controller:${CONTROLLER_VERSION} -f dockerfiles/controller/Dockerfile --build-arg version=${CONTROLLER_VERSION} .
