#!/bin/bash
set -e

query="
use deviceplane;
insert into users (id, email, password_hash, first_name, last_name) values ('usr', 'email@example.com', '5E884898DA28047151D0E56F8DC6292773603D0D6AABBDD62A11EF721D1542D8', 'First', 'Last');
insert into access_keys (id, user_id, hash) values ('key', 'usr', '2C70E12B7A0646F92279F427C7B38E7334D8E5389CFF167A1DC30E73F826B683');
insert into projects (id, name) values ('prj', 'testproject');
insert into memberships (user_id, project_id, level) values ('usr', 'prj', 'admin');
insert into applications (id, project_id, name) values ('app', 'prj', 'testapplication');
"

echo "$query" | mysql -h 127.0.0.1 -u user -ppass -P 3306
